# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    commit-message:
      prefix: "build(action)"
      prefix-development: "build(action-dev)"
      # include: "scope"
    open-pull-requests-limit: 10
    # ignore:
    #   - dependency-name: foo
    #     versions:
    #       - ">= 2.a, < 3"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    commit-message:
      prefix: "build(action)"
      prefix-development: "build(action-dev)"
      # include: "scope"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: github.com/swaggo/gin-swagger
      - dependency-name: github.com/swaggo/files
      - dependency-name: github.com/swaggo/swag/v2
      - dependency-name: github.com/sv-tools/openapi
      - dependency-name: github.com/urfave/cli/v3